import Link from "next/link";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import { getRequest } from "@/lib/store";
import { Icon } from "@/components/icon";
import { StatusBadge, UrgencyBadge } from "@/components/status-badge";
import { RequestActions } from "@/components/request-actions";

export const dynamic = "force-dynamic";

export default async function RequestDetailPage({ params }: { params: { id: string } }) {
  const owner = cookies().get("trlcs-owner")?.value;
  const request = owner ? await getRequest(params.id, owner) : null;
  if (!request) notFound();
  return <main className="mx-auto min-h-[calc(100vh-73px)] max-w-[940px] px-5 py-10 lg:px-8 lg:py-16"><Link href="/dashboard" className="focus-ring inline-flex items-center gap-2 text-sm font-semibold text-[#5f744a]"><Icon name="arrow" size={15} /> <span className="rotate-180">Back to requests</span></Link><div className="mt-8 flex flex-col gap-5 border-b border-[#dedfd9] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Support request</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{request.subject}</h1><p className="mt-3 text-sm text-[#70746d]">Opened {new Date(request.createdAt).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })}</p></div><div className="flex flex-wrap gap-2"><StatusBadge status={request.status} /><span className="rounded-full bg-[#f0f2ed] px-2.5 py-1 text-[11px] font-bold text-[#5d6259]">{request.category}</span><UrgencyBadge urgency={request.urgency} /></div></div><div className="mt-9 space-y-5"><div className="ml-auto max-w-[88%] rounded-2xl rounded-tr-sm bg-[#171916] p-5 text-white sm:max-w-[75%]"><p className="eyebrow !text-[#b8cba6]">You</p><p className="mt-2 whitespace-pre-line text-sm leading-7">{request.complaint}</p>{request.orderReference && <p className="mt-4 border-t border-white/15 pt-3 text-xs text-[#c2c8bc]">Order reference: {request.orderReference}</p>}</div>{request.aiResponse ? <div className="max-w-[88%] rounded-2xl rounded-tl-sm border border-[#dedfd9] bg-white p-5 sm:max-w-[75%]"><p className="eyebrow">The Racket Lifestyle support</p><p className="mt-3 whitespace-pre-line text-sm leading-7 text-[#31352e]">{request.aiResponse}</p></div> : <div className="rounded-2xl border border-[#eadfca] bg-[#fffaf0] p-5"><p className="flex items-center gap-2 font-semibold text-[#765a28]"><Icon name="clock" size={18} /> We’re still working on this</p><p className="mt-2 text-sm leading-6 text-[#765a28]">Your request is safely saved. Try again when the support service is available.</p></div>}</div>{request.summary && <div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#dedfd9] bg-white p-5"><p className="eyebrow">Summary</p><p className="mt-2 text-sm leading-6 text-[#50564d]">{request.summary}</p></div><div className="rounded-2xl border border-[#dedfd9] bg-white p-5"><p className="eyebrow">Next step</p><p className="mt-2 text-sm leading-6 text-[#50564d]">{request.safeNextStep}</p></div></div>}{request.needsEscalation && <div className="mt-5 flex gap-3 rounded-2xl border border-[#e6d7bb] bg-[#fffaf0] p-5 text-sm leading-6 text-[#765a28]"><Icon name="alert" size={19} /><p><strong>This request is flagged for escalation.</strong> Our support team should take a closer look rather than guess.</p></div>}<RequestActions request={request} /></main>;
}
