import Link from "next/link";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import { getRequest } from "@/lib/store";
import { Icon } from "@/components/icon";
import { StatusBadge, UrgencyBadge } from "@/components/status-badge";
import { RequestActions } from "@/components/request-actions";

export const dynamic = "force-dynamic";

export default async function RequestDetailPage({ params }: { params: { id: string } }) {
  const owner = cookies().get("trlcs-owner")?.value;
  const request = owner ? await getRequest(params.id, owner) : null;
  if (!request) notFound();
  return <main className="mx-auto min-h-[calc(100vh-73px)] max-w-[760px] px-4 py-8 lg:px-8 lg:py-12"><Link href="/dashboard" className="focus-ring inline-flex items-center gap-2 text-sm font-semibold text-[#5f744a]"><Icon name="arrow" size={15} /> <span className="rotate-180">Back to conversations</span></Link><div className="mt-7 flex items-center gap-3 border-b border-[#dedfd9] pb-6"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#dfead9] text-xs font-bold text-[#4f6845]">TR</div><div><p className="font-semibold">The Racket Lifestyle team</p><p className="text-xs text-[#70746d]">{request.subject}</p></div><div className="ml-auto flex flex-wrap justify-end gap-2"><StatusBadge status={request.status} /><UrgencyBadge urgency={request.urgency} /></div></div><div className="mt-8 space-y-5"><div className="ml-auto max-w-[88%] rounded-2xl rounded-tr-sm bg-[#171916] p-4 text-white sm:max-w-[75%]"><p className="text-xs font-semibold text-[#b8cba6]">You</p><p className="mt-2 whitespace-pre-line text-sm leading-7">{request.complaint}</p>{request.orderReference && <p className="mt-4 border-t border-white/15 pt-3 text-xs text-[#c2c8bc]">Order reference: {request.orderReference}</p>}</div>{request.aiResponse ? <div className="flex items-start gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#dfead9] text-[10px] font-bold text-[#4f6845]">TR</div><div className="max-w-[88%] rounded-2xl rounded-tl-sm border border-[#dedfd9] bg-white p-4 sm:max-w-[75%]"><p className="text-xs font-semibold text-[#4f6845]">The Racket Lifestyle team</p><p className="mt-3 whitespace-pre-line text-sm leading-7 text-[#31352e]">{request.aiResponse}</p></div></div> : <div className="rounded-2xl border border-[#eadfca] bg-[#fffaf0] p-5"><p className="flex items-center gap-2 font-semibold text-[#765a28]"><Icon name="clock" size={18} /> We’re still reading this</p><p className="mt-2 text-sm leading-6 text-[#765a28]">Your message is safely saved. Try again when our service is available.</p></div>}</div>{request.summary && <div className="mt-7 rounded-2xl border border-[#dedfd9] bg-white p-5"><p className="eyebrow">Our notes</p><p className="mt-2 text-sm leading-6 text-[#50564d]">{request.summary}</p><p className="eyebrow mt-5">Next step</p><p className="mt-1 text-sm leading-6 text-[#50564d]">{request.safeNextStep}</p></div>}{request.needsEscalation && <div className="mt-5 flex gap-3 rounded-2xl border border-[#e6d7bb] bg-[#fffaf0] p-5 text-sm leading-6 text-[#765a28]"><Icon name="alert" size={19} /><p><strong>We’ve passed this to the right people.</strong> Someone from our team should take a closer look.</p></div>}<RequestActions request={request} /></main>;
}
